//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hennery
{
    using System;
    using System.Collections.Generic;
    
    public partial class check_vaccine
    {
        public int ID_check_vaccine { get; set; }
        public Nullable<int> ID_vaccine { get; set; }
        public Nullable<int> ID_check { get; set; }
        public string quantity_vaccine { get; set; }
    
        public virtual check check { get; set; }
        public virtual vaccine vaccine { get; set; }
    }
}
