//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hennery
{
    using System;
    using System.Collections.Generic;
    
    public partial class consum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public consum()
        {
            this.item_store_consume = new HashSet<item_store_consume>();
        }
    
        public int ID_consum { get; set; }
        public Nullable<System.DateTime> consum_date { get; set; }
        public string consum_type { get; set; }
        public Nullable<int> ID_troop { get; set; }
    
        public virtual troop troop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item_store_consume> item_store_consume { get; set; }
    }
}
