//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hennery
{
    using System;
    using System.Collections.Generic;
    
    public partial class hengar_troop
    {
        public int ID_hengar_troop { get; set; }
        public Nullable<int> ID_hengar { get; set; }
        public Nullable<int> ID_troop { get; set; }
    
        public virtual hengar hengar { get; set; }
        public virtual troop troop { get; set; }
    }
}
