//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hennery
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HenneryDb : DbContext
    {
        public HenneryDb()
            : base("name=HenneryDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<check_vaccine> check_vaccine { get; set; }
        public virtual DbSet<check> checks { get; set; }
        public virtual DbSet<consum> consums { get; set; }
        public virtual DbSet<foodItem> foodItems { get; set; }
        public virtual DbSet<hengar> hengars { get; set; }
        public virtual DbSet<hengar_troop> hengar_troop { get; set; }
        public virtual DbSet<import> imports { get; set; }
        public virtual DbSet<import_item> import_item { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<item_store> item_store { get; set; }
        public virtual DbSet<item_store_consume> item_store_consume { get; set; }
        public virtual DbSet<item_store_mix> item_store_mix { get; set; }
        public virtual DbSet<machine> machines { get; set; }
        public virtual DbSet<mix> mixes { get; set; }
        public virtual DbSet<mix_foodItem> mix_foodItem { get; set; }
        public virtual DbSet<prepration> preprations { get; set; }
        public virtual DbSet<produce> produces { get; set; }
        public virtual DbSet<repair> repairs { get; set; }
        public virtual DbSet<store> stores { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<troop> troops { get; set; }
        public virtual DbSet<vaccine> vaccines { get; set; }
    
        public virtual int delete_hengar(Nullable<int> iD_hengar)
        {
            var iD_hengarParameter = iD_hengar.HasValue ?
                new ObjectParameter("ID_hengar", iD_hengar) :
                new ObjectParameter("ID_hengar", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_hengar", iD_hengarParameter);
        }
    
        public virtual int delete_item(Nullable<int> iD_item)
        {
            var iD_itemParameter = iD_item.HasValue ?
                new ObjectParameter("ID_item", iD_item) :
                new ObjectParameter("ID_item", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_item", iD_itemParameter);
        }
    
        public virtual int delete_machine(Nullable<int> iD_machine)
        {
            var iD_machineParameter = iD_machine.HasValue ?
                new ObjectParameter("ID_machine", iD_machine) :
                new ObjectParameter("ID_machine", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_machine", iD_machineParameter);
        }
    
        public virtual int delete_store(Nullable<int> iD_store)
        {
            var iD_storeParameter = iD_store.HasValue ?
                new ObjectParameter("ID_store", iD_store) :
                new ObjectParameter("ID_store", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_store", iD_storeParameter);
        }
    
        public virtual int delete_supplier(Nullable<int> iD_supplier)
        {
            var iD_supplierParameter = iD_supplier.HasValue ?
                new ObjectParameter("ID_supplier", iD_supplier) :
                new ObjectParameter("ID_supplier", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_supplier", iD_supplierParameter);
        }
    
        public virtual int delete_troop(Nullable<int> iD_troop)
        {
            var iD_troopParameter = iD_troop.HasValue ?
                new ObjectParameter("ID_troop", iD_troop) :
                new ObjectParameter("ID_troop", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_troop", iD_troopParameter);
        }
    
        public virtual int insert_hengar(string hengar_space, string kind, string hengar_name)
        {
            var hengar_spaceParameter = hengar_space != null ?
                new ObjectParameter("hengar_space", hengar_space) :
                new ObjectParameter("hengar_space", typeof(string));
    
            var kindParameter = kind != null ?
                new ObjectParameter("kind", kind) :
                new ObjectParameter("kind", typeof(string));
    
            var hengar_nameParameter = hengar_name != null ?
                new ObjectParameter("hengar_name", hengar_name) :
                new ObjectParameter("hengar_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_hengar", hengar_spaceParameter, kindParameter, hengar_nameParameter);
        }
    
        public virtual int insert_item(string item_name, string item_kind)
        {
            var item_nameParameter = item_name != null ?
                new ObjectParameter("item_name", item_name) :
                new ObjectParameter("item_name", typeof(string));
    
            var item_kindParameter = item_kind != null ?
                new ObjectParameter("item_kind", item_kind) :
                new ObjectParameter("item_kind", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_item", item_nameParameter, item_kindParameter);
        }
    
        public virtual int insert_machine(Nullable<int> iD_machine, string company, string discreption, Nullable<int> serial_number)
        {
            var iD_machineParameter = iD_machine.HasValue ?
                new ObjectParameter("ID_machine", iD_machine) :
                new ObjectParameter("ID_machine", typeof(int));
    
            var companyParameter = company != null ?
                new ObjectParameter("company", company) :
                new ObjectParameter("company", typeof(string));
    
            var discreptionParameter = discreption != null ?
                new ObjectParameter("discreption", discreption) :
                new ObjectParameter("discreption", typeof(string));
    
            var serial_numberParameter = serial_number.HasValue ?
                new ObjectParameter("serial_number", serial_number) :
                new ObjectParameter("serial_number", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_machine", iD_machineParameter, companyParameter, discreptionParameter, serial_numberParameter);
        }
    
        public virtual int insert_store(Nullable<int> iD_hengar, Nullable<int> iD_store, string store_name, Nullable<float> space, Nullable<float> temperature, Nullable<float> wet, Nullable<bool> light)
        {
            var iD_hengarParameter = iD_hengar.HasValue ?
                new ObjectParameter("ID_hengar", iD_hengar) :
                new ObjectParameter("ID_hengar", typeof(int));
    
            var iD_storeParameter = iD_store.HasValue ?
                new ObjectParameter("ID_store", iD_store) :
                new ObjectParameter("ID_store", typeof(int));
    
            var store_nameParameter = store_name != null ?
                new ObjectParameter("store_name", store_name) :
                new ObjectParameter("store_name", typeof(string));
    
            var spaceParameter = space.HasValue ?
                new ObjectParameter("Space", space) :
                new ObjectParameter("Space", typeof(float));
    
            var temperatureParameter = temperature.HasValue ?
                new ObjectParameter("temperature", temperature) :
                new ObjectParameter("temperature", typeof(float));
    
            var wetParameter = wet.HasValue ?
                new ObjectParameter("wet", wet) :
                new ObjectParameter("wet", typeof(float));
    
            var lightParameter = light.HasValue ?
                new ObjectParameter("light", light) :
                new ObjectParameter("light", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_store", iD_hengarParameter, iD_storeParameter, store_nameParameter, spaceParameter, temperatureParameter, wetParameter, lightParameter);
        }
    
        public virtual int insert_supplier(string supplier_name, string phone, string office_telephone)
        {
            var supplier_nameParameter = supplier_name != null ?
                new ObjectParameter("supplier_name", supplier_name) :
                new ObjectParameter("supplier_name", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var office_telephoneParameter = office_telephone != null ?
                new ObjectParameter("office_telephone", office_telephone) :
                new ObjectParameter("office_telephone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_supplier", supplier_nameParameter, phoneParameter, office_telephoneParameter);
        }
    
        public virtual int insert_troop(Nullable<int> iD_troop, Nullable<int> number, Nullable<int> weight, string kind, Nullable<int> current_quantity)
        {
            var iD_troopParameter = iD_troop.HasValue ?
                new ObjectParameter("ID_troop", iD_troop) :
                new ObjectParameter("ID_troop", typeof(int));
    
            var numberParameter = number.HasValue ?
                new ObjectParameter("number", number) :
                new ObjectParameter("number", typeof(int));
    
            var weightParameter = weight.HasValue ?
                new ObjectParameter("weight", weight) :
                new ObjectParameter("weight", typeof(int));
    
            var kindParameter = kind != null ?
                new ObjectParameter("kind", kind) :
                new ObjectParameter("kind", typeof(string));
    
            var current_quantityParameter = current_quantity.HasValue ?
                new ObjectParameter("current_quantity", current_quantity) :
                new ObjectParameter("current_quantity", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_troop", iD_troopParameter, numberParameter, weightParameter, kindParameter, current_quantityParameter);
        }
    
        public virtual ObjectResult<select_all_hengar_Result> select_all_hengar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_all_hengar_Result>("select_all_hengar");
        }
    
        public virtual ObjectResult<select_all_item_in_store_Result> select_all_item_in_store(Nullable<int> iD_store)
        {
            var iD_storeParameter = iD_store.HasValue ?
                new ObjectParameter("ID_store", iD_store) :
                new ObjectParameter("ID_store", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_all_item_in_store_Result>("select_all_item_in_store", iD_storeParameter);
        }
    
        public virtual ObjectResult<select_all_items_Result> select_all_items()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_all_items_Result>("select_all_items");
        }
    
        public virtual ObjectResult<select_all_stores_Result> select_all_stores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_all_stores_Result>("select_all_stores");
        }
    
        public virtual ObjectResult<select_all_troop_Result> select_all_troop()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_all_troop_Result>("select_all_troop");
        }
    
        public virtual ObjectResult<select_daeth_troop_Result> select_daeth_troop()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_daeth_troop_Result>("select_daeth_troop");
        }
    
        public virtual ObjectResult<select_empty_hengar_Result> select_empty_hengar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_empty_hengar_Result>("select_empty_hengar");
        }
    
        public virtual ObjectResult<select_expiration_date_of_item_Result> select_expiration_date_of_item()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_expiration_date_of_item_Result>("select_expiration_date_of_item");
        }
    
        public virtual ObjectResult<select_info_of_current_hengar_and_its_troop_Result> select_info_of_current_hengar_and_its_troop()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_info_of_current_hengar_and_its_troop_Result>("select_info_of_current_hengar_and_its_troop");
        }
    
        public virtual ObjectResult<select_itemQuantity_Result> select_itemQuantity()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_itemQuantity_Result>("select_itemQuantity");
        }
    
        public virtual ObjectResult<select_machine_notWork_Result> select_machine_notWork()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_machine_notWork_Result>("select_machine_notWork");
        }
    
        public virtual ObjectResult<select_machine_work_Result> select_machine_work()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_machine_work_Result>("select_machine_work");
        }
    
        public virtual ObjectResult<select_quntity_of_daily_consum_Result> select_quntity_of_daily_consum()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_quntity_of_daily_consum_Result>("select_quntity_of_daily_consum");
        }
    
        public virtual ObjectResult<select_store_of_hengar_and_current_items_Result> select_store_of_hengar_and_current_items()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_store_of_hengar_and_current_items_Result>("select_store_of_hengar_and_current_items");
        }
    
        public virtual ObjectResult<select_StoreInfo_Result> select_StoreInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_StoreInfo_Result>("select_StoreInfo");
        }
    
        public virtual ObjectResult<select_StoreItems_Result> select_StoreItems(Nullable<int> storeId)
        {
            var storeIdParameter = storeId.HasValue ?
                new ObjectParameter("StoreId", storeId) :
                new ObjectParameter("StoreId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_StoreItems_Result>("select_StoreItems", storeIdParameter);
        }
    
        public virtual ObjectResult<select_the_better_supplier_Result> select_the_better_supplier()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_the_better_supplier_Result>("select_the_better_supplier");
        }
    
        public virtual ObjectResult<select_troop_Preduces_Result> select_troop_Preduces(Nullable<int> id_troop)
        {
            var id_troopParameter = id_troop.HasValue ?
                new ObjectParameter("id_troop", id_troop) :
                new ObjectParameter("id_troop", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_troop_Preduces_Result>("select_troop_Preduces", id_troopParameter);
        }
    
        public virtual ObjectResult<select_troop_vaccine_Result> select_troop_vaccine()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_troop_vaccine_Result>("select_troop_vaccine");
        }
    
        public virtual ObjectResult<select_troopConsumItems_Result> select_troopConsumItems(Nullable<int> consumId, Nullable<int> troopId)
        {
            var consumIdParameter = consumId.HasValue ?
                new ObjectParameter("consumId", consumId) :
                new ObjectParameter("consumId", typeof(int));
    
            var troopIdParameter = troopId.HasValue ?
                new ObjectParameter("troopId", troopId) :
                new ObjectParameter("troopId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_troopConsumItems_Result>("select_troopConsumItems", consumIdParameter, troopIdParameter);
        }
    
        public virtual ObjectResult<selectTroopCunsums_Result> selectTroopCunsums(Nullable<int> troopId)
        {
            var troopIdParameter = troopId.HasValue ?
                new ObjectParameter("TroopId", troopId) :
                new ObjectParameter("TroopId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectTroopCunsums_Result>("selectTroopCunsums", troopIdParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int update_hengar(Nullable<int> iD_hengar, string hengar_space, string kind, string hengar_name)
        {
            var iD_hengarParameter = iD_hengar.HasValue ?
                new ObjectParameter("ID_hengar", iD_hengar) :
                new ObjectParameter("ID_hengar", typeof(int));
    
            var hengar_spaceParameter = hengar_space != null ?
                new ObjectParameter("hengar_space", hengar_space) :
                new ObjectParameter("hengar_space", typeof(string));
    
            var kindParameter = kind != null ?
                new ObjectParameter("kind", kind) :
                new ObjectParameter("kind", typeof(string));
    
            var hengar_nameParameter = hengar_name != null ?
                new ObjectParameter("hengar_name", hengar_name) :
                new ObjectParameter("hengar_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_hengar", iD_hengarParameter, hengar_spaceParameter, kindParameter, hengar_nameParameter);
        }
    
        public virtual int update_store(Nullable<int> iD_store, Nullable<int> iD_hengar, string store_name, Nullable<float> space, Nullable<float> temperature, Nullable<float> wet, Nullable<bool> light)
        {
            var iD_storeParameter = iD_store.HasValue ?
                new ObjectParameter("ID_store", iD_store) :
                new ObjectParameter("ID_store", typeof(int));
    
            var iD_hengarParameter = iD_hengar.HasValue ?
                new ObjectParameter("ID_hengar", iD_hengar) :
                new ObjectParameter("ID_hengar", typeof(int));
    
            var store_nameParameter = store_name != null ?
                new ObjectParameter("store_name", store_name) :
                new ObjectParameter("store_name", typeof(string));
    
            var spaceParameter = space.HasValue ?
                new ObjectParameter("space", space) :
                new ObjectParameter("space", typeof(float));
    
            var temperatureParameter = temperature.HasValue ?
                new ObjectParameter("temperature", temperature) :
                new ObjectParameter("temperature", typeof(float));
    
            var wetParameter = wet.HasValue ?
                new ObjectParameter("wet", wet) :
                new ObjectParameter("wet", typeof(float));
    
            var lightParameter = light.HasValue ?
                new ObjectParameter("light", light) :
                new ObjectParameter("light", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_store", iD_storeParameter, iD_hengarParameter, store_nameParameter, spaceParameter, temperatureParameter, wetParameter, lightParameter);
        }
    
        public virtual int update_troop(Nullable<int> iD_troop, Nullable<int> number, Nullable<int> weight, string kind, Nullable<int> current_quantity)
        {
            var iD_troopParameter = iD_troop.HasValue ?
                new ObjectParameter("ID_troop", iD_troop) :
                new ObjectParameter("ID_troop", typeof(int));
    
            var numberParameter = number.HasValue ?
                new ObjectParameter("number", number) :
                new ObjectParameter("number", typeof(int));
    
            var weightParameter = weight.HasValue ?
                new ObjectParameter("weight", weight) :
                new ObjectParameter("weight", typeof(int));
    
            var kindParameter = kind != null ?
                new ObjectParameter("kind", kind) :
                new ObjectParameter("kind", typeof(string));
    
            var current_quantityParameter = current_quantity.HasValue ?
                new ObjectParameter("current_quantity", current_quantity) :
                new ObjectParameter("current_quantity", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_troop", iD_troopParameter, numberParameter, weightParameter, kindParameter, current_quantityParameter);
        }
    
        public virtual ObjectResult<select_Current_troop_Result> select_Current_troop()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_Current_troop_Result>("select_Current_troop");
        }
    
        public virtual ObjectResult<select_expiration_date_of_item_forStore_Result> select_expiration_date_of_item_forStore(Nullable<int> soreId)
        {
            var soreIdParameter = soreId.HasValue ?
                new ObjectParameter("SoreId", soreId) :
                new ObjectParameter("SoreId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_expiration_date_of_item_forStore_Result>("select_expiration_date_of_item_forStore", soreIdParameter);
        }
    
        public virtual ObjectResult<selectHengarWithId_Result> selectHengarWithId(Nullable<int> hengarId)
        {
            var hengarIdParameter = hengarId.HasValue ?
                new ObjectParameter("HengarId", hengarId) :
                new ObjectParameter("HengarId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectHengarWithId_Result>("selectHengarWithId", hengarIdParameter);
        }
    
        public virtual ObjectResult<selectAgeAndProduce_Result> selectAgeAndProduce()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectAgeAndProduce_Result>("selectAgeAndProduce");
        }
    
        public virtual ObjectResult<TroopMustBeSold_Result> TroopMustBeSold()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TroopMustBeSold_Result>("TroopMustBeSold");
        }
    }
}
