//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hennery
{
    using System;
    using System.Collections.Generic;
    
    public partial class import_item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public import_item()
        {
            this.item_store = new HashSet<item_store>();
        }
    
        public int ID_import_item { get; set; }
        public Nullable<int> ID_item { get; set; }
        public Nullable<int> ID_import { get; set; }
        public Nullable<int> quntity { get; set; }
        public float price { get; set; }
        public Nullable<System.DateTime> produce_date { get; set; }
        public Nullable<System.DateTime> expiryDate { get; set; }
    
        public virtual import import { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item_store> item_store { get; set; }
        public virtual machine machine { get; set; }
        public virtual troop troop { get; set; }
    }
}
