//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hennery
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public item_store()
        {
            this.item_store_consume = new HashSet<item_store_consume>();
            this.item_store_mix = new HashSet<item_store_mix>();
        }
    
        public int ID_item_store { get; set; }
        public Nullable<int> ID_produce { get; set; }
        public Nullable<int> ID_import_item { get; set; }
        public Nullable<int> ID_mix_foodItem { get; set; }
        public Nullable<int> ID_store { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual import_item import_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item_store_consume> item_store_consume { get; set; }
        public virtual mix_foodItem mix_foodItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item_store_mix> item_store_mix { get; set; }
        public virtual produce produce { get; set; }
        public virtual store store { get; set; }
    }
}
