//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hennery
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_store_mix
    {
        public int ID_item_store_mix { get; set; }
        public Nullable<int> ID_mix_foodItem { get; set; }
        public Nullable<int> ID_item_store { get; set; }
    
        public virtual item_store item_store { get; set; }
        public virtual mix_foodItem mix_foodItem { get; set; }
    }
}
