//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hennery
{
    using System;
    using System.Collections.Generic;
    
    public partial class mix_foodItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mix_foodItem()
        {
            this.item_store = new HashSet<item_store>();
            this.item_store_mix = new HashSet<item_store_mix>();
        }
    
        public int ID_mix_foodItem { get; set; }
        public Nullable<int> ID_fooditem { get; set; }
        public Nullable<int> ID_mix { get; set; }
    
        public virtual foodItem foodItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item_store> item_store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item_store_mix> item_store_mix { get; set; }
        public virtual mix mix { get; set; }
    }
}
