//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hennery
{
    using System;
    using System.Collections.Generic;
    
    public partial class store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public store()
        {
            this.item_store = new HashSet<item_store>();
        }
    
        public int ID_store { get; set; }
        public Nullable<int> ID_hengar { get; set; }
        public string Store_name { get; set; }
        public Nullable<float> Space { get; set; }
        public Nullable<float> temperature { get; set; }
        public Nullable<float> wet { get; set; }
        public Nullable<bool> light { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item_store> item_store { get; set; }
    }
}
