//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hennery
{
    using System;
    using System.Collections.Generic;
    
    public partial class troop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public troop()
        {
            this.checks = new HashSet<check>();
            this.consums = new HashSet<consum>();
            this.hengar_troop = new HashSet<hengar_troop>();
            this.produces = new HashSet<produce>();
        }
    
        public int ID_troop { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<int> weight { get; set; }
        public string kind { get; set; }
        public Nullable<int> current_quntity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<check> checks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consum> consums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hengar_troop> hengar_troop { get; set; }
        public virtual import_item import_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<produce> produces { get; set; }
    }
}
